"""empty message

Revision ID: 05529d3f623d
Revises: 1c7970fe994a
Create Date: 2022-03-06 09:09:50.631116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05529d3f623d'
down_revision = '1c7970fe994a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'password')
    # ### end Alembic commands ###
